language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kaushikbarun/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kaushikbarun/react-test npm test -- --coverage

after_success:
  - docker build -t kaushikbarun/multi-client ./client
  - docker build -t kaushikbarun/multi-nginx ./nginx
  - docker build -t kaushikbarun/multi-server ./server
  - docker build -t kaushikbarun/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images to docker hub
  - docker push kaushikbarun/multi-client
  - docker push kaushikbarun/multi-nginx
  - docker push kaushikbarun/multi-server
  - docker push kaushikbarun/multi-worker